Added API for creation new custom wepons
modweaver/modweaver pull request #2
Opened 2024-01-23 06:36 UTC by AnriiAndrushko

2024-01-23 09:34 UTC, AnriiAndrushko commented
fixed bug, now must work properly

2024-01-23 16:27 UTC, Ecorous requested changes
Please don't change things that aren't related to your PR. I've marked those out where I can. I won't merge this until those are fixed

2024-01-23 16:27 UTC, Ecorous commented on modweaver.api/API/NewWeaponsManager.cs
> +        public enum WeaponType {
Do we really need to define our own enum?

2024-01-23 16:27 UTC, Ecorous commented on modweaver.api/API/NewWeaponsManager.cs
> +        private static uint _prefabHandlerId = 7777; //TODO: fix possible collision
I'm not sure how we'll fix this- but I think it's fine for now. If we run into any issues then this'll need to be changed.

2024-01-23 16:27 UTC, Ecorous commented on modweaver.api/API/WeaponHandler.cs
> +internal class WeaponNetworkPrefabInstanceHandler : INetworkPrefabInstanceHandler {
I'd suggest moving internal classes out of the API folder

2024-01-23 16:27 UTC, Ecorous commented on modweaver.testmod/ModMain.cs
> -            //test logger
Why did you delete the logging tests? It's important to test all aspects of the api in the testmod.

2024-01-23 16:27 UTC, Ecorous commented on modweaver.testmod/ModMain.cs
> -            ui.CreateTitle("I'm a cool mod :3");
Same with this, why delete stuff that isn't related?

2024-01-23 16:27 UTC, Ecorous commented on modweaver.testmod/ModMain.cs
> +                __instance.textMesh.text += $"\n<color=red> Testmod v0.0.1 by YourName</color>";
Also with this, changing things for no real reason

2024-01-24 08:55 UTC, AnriiAndrushko commented on modweaver.api/API/NewWeaponsManager.cs
> +        public enum WeaponType {
There is already enum in Weapon.WeaponType but it only describe general type and my enum describe all existing weapons and corresponds to their index in array

2024-01-24 09:57 UTC, AnriiAndrushko commented
now must be fine, but when i tryed to test it i figure out that harmony patches not calling from API lib so that code that patch weapons into game never executed, i actually dont know how to fix this

2024-01-24 10:31 UTC, AnriiAndrushko commented
i think it will be good to create separate "indev" branch and fix it there

2024-02-01 21:10 UTC, closed without merging

2024-02-01 21:10 UTC, AnriiAndrushko commented
Moving this PR into API repo